version: "3.6"

services:
    web:
        build: 
            context: . # context tells it where to get projects from
            dockerfile: Dockerfile.dev
        ports: 
            - "80:3000"
        volumes:
            - /app/node_modules #keeps that file in the dir so not overwritten by next command
            - .:/app # maps the local dir (.  or pwd) [present working directory] to the /app folder
            ##this is to allow for hot reloading on dev servers

    tests:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - .:/app
        command: ["npm", "run", "test"]